server:
  port: 8082

spring:
  datasource:
    url: 'jdbc:postgresql://analytics_db_prod:5432/couponmanager'
    username: 'admin'
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: 'update'

amqp:
  exchange:
    analytics: 'analytics.${couponmanager.instance}.topic'
  queue:
    checkout: 'checkout.${couponmanager.instance}.queue'