server:
  port: 8080

spring:
  datasource:
    url: 'jdbc:postgresql://usermanager_db:$5432/usermanager'
    username: 'admin'
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: 'update'