server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    consul:
      discovery:
        enabled: true
        discovery:
          # Get only services that are passing the health check
          query-passing: true
    gateway:
      routes:
        - id: usermanager
          uri: lb://usermanager/
          predicates:
            - Path=/register,/api/users/**,/login
        - id: couponmanager
          uri: lb://couponmanager/
          predicates:
            - Path=/coupons/**,/products,/product-groups
          # filters:
          #   - SaveSession
      #globalcors:
      #  cors-configurations:
      #    '[/**]':
      #      allowedOrigins: "http://localhost:3000"
      #      allowedHeaders:
      #        - "*"
      #      allowedMethods:
      #        - "GET"
      #        - "POST"
      #       - "OPTIONS"
      default-filters:
        # built-in Retry design pattern!
        - name: Retry
          args:
            retries: 3
            methods: GET,POST

# Uncomment the configuration below if you want to enable route matching logs
#logging:
#  level:
#    org.springframework.cloud.gateway.handler.predicate: trace