server:
  port: 8000

spring:
  cloud:
    consul:
      discovery:
        enabled: true
        discovery:
          query-passing: true
    gateway:
      routes:
        - id: usermanager
          uri: lb://usermanager/
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
        - id: couponmanager
          uri: lb://couponmanager/
          predicates:
            - Path=/api/couponmanager/**
          filters:
            - RewritePath=/api/couponmanager(?<segment>/?.*), $\{segment}
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST,PUT,DELETE

# Uncomment the configuration below if you want to enable route matching logs
#logging:
#  level:
#    org.springframework.cloud.gateway.handler.predicate: trace